#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "Create Securitygroup"

#debug block
  ./showENV.sh
#

echo Create Securitygroup >> ${VpcId}-build-log.json
 securitygroup=$(aws ec2 create-security-group --group-name "SSH-${VPC_stack}-${EC2_stack}" --description "Security Group for SSH Access" --vpc-id ${VpcId} | grep GroupId | cut -d':' -f2 | tr -d '"| |,' )

aws ec2 describe-security-groups --group-id ${securitygroup} >> ${VpcId}-build-log.json

echo SecurityGroup Values >> ${VpcId}-build-log.json

# Hot 3 -- DLT Home and Work Plus Manan
 #aws ec2 authorize-security-group-ingress --group-id ${securitygroup} --protocol tcp --port 22 --cidr "98.251.81.179/32"  # DLT Home
 #aws ec2 authorize-security-group-ingress --group-id ${securitygroup} --protocol tcp --port 22 --cidr "173.46.67.139/32"  # DLT Work
 #aws ec2 authorize-security-group-ingress --group-id ${securitygroup} --protocol tcp --port 22 --cidr "34.239.243.201/32" # Manan WS

# VPN 3 via NORD
 #aws ec2 authorize-security-group-ingress --group-id ${securitygroup} --protocol tcp --port 22 --cidr "68.235.53.221/32" # NORD Chicago
 #aws ec2 authorize-security-group-ingress --group-id ${securitygroup} --protocol tcp --port 22 --cidr "107.172.254.2/32" # NORD Buffalo
 #aws ec2 authorize-security-group-ingress --group-id ${securitygroup} --protocol tcp --port 22 --cidr "209.58.139.29/32" # NORD SanJose

 #
 aws ec2 create-tags --resources ${PUBnet1} --tags Key=Name,Value="${VPC_stack}-${EC2_stack}-Public"
 aws ec2 create-tags --resources ${PUBnet1} --tags Key=Stack,Value="${VPC_stack}-${EC2_stack}"

 ## double up

# update creatCFG file
  echo "export SGssh=${securitygroup}" >> ${build_CFG}

 #
 aws ec2 create-tags --resources ${PRVnet1} --tags Key=Name,Value="${VPC_stack}-${EC2_stack}-Private"
 aws ec2 create-tags --resources ${PRVnet1} --tags Key=Stack,Value="${VPC_stack}-${EC2_stack}"

 ## double up

 aws ec2 describe-security-groups --group-ids ${securitygroup} >> ${VpcId}-build-log.json

# fin 0
