#!/usr/bin/env bash

#
# Create VPC, InternetGatewayId, Public & Private subnets with EC2
#

# jorgedlt@gmail.com - 03 MAR 2017 / 02 JUL 2017
# additional private documentation
# see - https://docs.google.com/document/d/1RdN2hbPeSvrCDTa76iZyExmVhF-Ct9iv-TcFNMRZwSU/edit

# Load ENV parameters
source ./createCFG.env

echo "Create PRIVATE subnet "

#debug block
  ./showENV.sh
#

#
 privateSub2=$(aws ec2 create-subnet --vpc-id "${VpcId}" --cidr-block "${PRV2cidr}" --availability-zone ${PRV2azone} | grep 'SubnetId' | cut -d':' -f2 | tr -d '"| |,')
 aws ec2 create-tags --resources "${privateSub2}" --tags Key=Name,Value=privateSub2-${VPC_stack}

echo ${privateSub2} >> ${VpcId}-build-log.json
aws ec2 describe-subnets --subnet-ids ${privateSub2} >> ${VpcId}-build-log.json

# update creatCFG file
  echo "export PRVnet2=${privateSub2}" >> ${build_CFG}

echo "Select Availability Zone" >> ${VpcId}-build-log.json
AZone1=$(aws ec2 describe-subnets --subnet-ids ${privateSub2} | grep AvailabilityZone | cut -d':' -f2 | tr -d '"| |,')

# update creatCFG file
  echo "export AZone2=${AZone2}" >> ${build_CFG}

# fin 0
